[workspace]
members = [
    "docker-rs",
    "dps",
    "edgelet-config",
    "edgelet-core",
    "edgelet-docker",
    "edgelet-hosting",
    "edgelet-hsm",
    "edgelet-http",
    "edgelet-http-hosting",
    "edgelet-http-mgmt",
    "edgelet-http-workload",
    "edgelet-iothub",
    "edgelet-kube",
    "edgelet-test-utils",
    "edgelet-utils",
    "hosting",
    "kube-client",
    "hsm-rs",
    "hsm-sys",
    "hyper-named-pipe",
    "iotedge",
    "iotedged",
    "iotedged-eventlog-messages",
    "iotedge-diagnostics",
    "iothubservice",
    "management",
    "mini-sntp",
    "provisioning",
    "systemd",
    "tokio-named-pipe",
    "win-logger",
]
