/*
 * IoT Edge Hosting Environment API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-04-10
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use failure::err_msg;
use failure::Error;
use hyper::client::Connect;
use hyper::{Client, Uri};

pub struct Configuration<C: Connect> {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub client: Client<C>,
    pub uri_composer: Box<Fn(&str, &str) -> Result<Uri, Error>>,
    pub sas_token: Option<String>,
}

impl<C: Connect> Configuration<C> {
    pub fn new(client: Client<C>) -> Configuration<C> {
        Configuration {
            base_path: "http://localhost".to_owned(),
            user_agent: Some("Swagger-Codegen/2019-04-10/rust".to_owned()),
            client: client,
            uri_composer: Box::new(|base_path, path| {
                format!("{}{}", base_path, path)
                    .parse()
                    .map_err(|_| format_err!("Url parse error"))
            }),
            sas_token: None,
        }
    }
}
